apiVersion: v1
kind: Service
metadata:
  name: ms-users-service
spec:
  selector:
    app: ms-users
  ports:
    - protocol: TCP
      port: 3000 #
      targetPort: 3000 # Puerto que el pod estará escuchando
      nodePort: 30000 # Puerto que la máquina estará escuchando
  type: NodePort
